# Generated by Django 5.2.11 on 2026-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0002_ticket_deleted_at_ticket_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
