# Generated by Django 5.2.11 on 2026-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0007_ticketattachment_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
