# Generated by Django 5.2.11 on 2026-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0008_ticket_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='tiket.department'),
        ),
    ]
